import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_us': {
          'Login': "Login",
          "nick name": 'nick name',
          "Good Morning": "Good Morning",
          "Good Afternoon": "Good Afternoon",
          "Good Evening": "Good evening",
          "Send ": "Send ",
          "Request": "Request",
          'Transactions': "Transactions",
          'Logout': "Logout",
          'Back': "Back ",
          "Don't have an account? ": "Don't have an account?",
          'Transactions': "Transactions history ",
          'enter amount here': "enter amount here",
          'Balance': "Balance",
          'pin number': "pin number",
          "Enter 6 digits pin": "Enter 6 digits pin",
          'pin': "pin",
          "Register": "Register",
          "Enter nick name": "Enter nick name",
          "Balance": "Balance",
          "See More": "See More",
          "Profile": "Profile",
          "User Name": "User Name",
          "Full Name": "Full Name",
          "Mobile": "Mobile",
          "U p i Id": "U p i Id",
          "Delete Account": "Delete Account",
          "Enter Your Pin": "Enter Your Pin",
          "Current Balance": "Current Balance",
          "enter upi id": "enter upi id",
          "enter recevier name": "enter recevier name"
        },
        'te_IN': {
          'Login': "ప్రవేశించండి",
          "nick name": "మారుపేరు",
          "Good Morning": "శుభోదయం",
          "Good Afternoon": "శుభ మద్యాహ్నం",
          "Good Evening": "శుభ సాయంత్రం",
          "Send ": "పంపండి",
          "Request": "అభ్యర్థన",
          "Don't have an account? ": "ఖాతా లేదా?",
          "Register": "నమోదు చేసుకోండి",
          "Enter 6 digits pin": "6 అంకెల పిన్‌ని నమోదు చేయండి",
          "Transactions": "లావాదేవీలు",
          "Enter nick name": "మారుపేరును నమోదు చేయండి",
          "Balance": "సంతులనం",
          "See More": "ఇంకా చూడండి",
          "Profile": "ప్రొఫైల్",
          "User Name": "వినియోగదారు పేరు",
          "Full Name": "పూర్తి పేరు",
          "Mobile": "మొబైల్",
          "U p i Id": "U p i Id",
          "Delete Account": "ఖాతాను తొలగించండి",
          "Enter Your Pin": "మీ పిన్‌ని నమోదు చేయండి",
          "Current Balance": "ప్రస్తుత నిల్వ",
          "enter upi id": "upi idని నమోదు చేయండి",
          "enter recevier name": "రిసీవియర్ పేరు నమోదు చేయండి"
        }
      };
}
